title: Songyang Jiang's Homepage
page-top-title: Songyang Jiang
top-section-bg-text: Be what you wanna be
home-subtitle: Songyang Jiang&ensp;|&ensp; Undergraduate @ XJTU School of Electrical Engineering
copyright-text: '&copy; Songyang Jiang 2023-2025. All Rights Reserved.'
