title: Songyang Jiang's Homepage 
page-top-title: 江松阳&ensp;|&ensp Songyang Jiang;
top-section-bg-text: Die Zukunft gehört denen, die sie verändern
home-subtitle: 江松阳&ensp;|&ensp Songyang Jiang; 
copyright-text: '&copy; Songyang Jiang 2023-2025. All Rights Reserved.'
